version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: website-builder
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis will be replaced by Valkey later
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres-data:
  redis-data: